all:step1 step2 step3

step1: step1.c
	gcc -pedantic -std=gnu99 -ggdb -Wall -Werror step1.c -o step1
step2: step2.c
	gcc -pedantic -std=gnu99 -ggdb -Wall -Werror step2.c -o step2
step3: step3.c
	gcc -pedantic -std=gnu99 -ggdb -Wall -Werror step3.c -o step3
